# Generated by Django 5.0.4 on 2024-05-05 21:05

import common.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('billing_email', models.EmailField(max_length=254)),
                ('billing_details', models.TextField(blank=True)),
                ('country_code', models.PositiveIntegerField()),
                ('phone', models.PositiveIntegerField()),
                ('tax_id', models.CharField(max_length=20)),
                ('failed_payment_notifications', models.BooleanField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'indexes': [common.models.PostgresIndex(fields=['uuid'], name='account_account_uuid_idx'), common.models.PostgresIndex(fields=['created'], name='account_account_created_idx'), common.models.PostgresIndex(fields=['updated'], name='account_account_updated_idx')],
            },
        ),
    ]
