# Generated by Django 5.0.6 on 2024-05-28 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_invitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='joined',
            field=models.BooleanField(editable=False),
        ),
    ]
