# Generated by Django 5.0.6 on 2024-05-31 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_invitation_email_alter_invitation_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='joined',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
