# Generated by Django 5.0.6 on 2024-06-23 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_account_contract_signed_document_signed_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Español')], default='en', max_length=2),
        ),
    ]
