# Generated by Django 5.0.6 on 2024-06-11 14:04

import common.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_invitation_joined'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='signature_request_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='document',
            name='signed',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddIndex(
            model_name='document',
            index=common.models.PostgresIndex(fields=['uuid'], name='account_document_uuid_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=common.models.PostgresIndex(fields=['created'], name='account_document_created_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=common.models.PostgresIndex(fields=['updated'], name='account_document_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['signature_request_id'], name='account_doc_signatu_adcd5b_idx'),
        ),
    ]
