# Generated by Django 5.0.6 on 2024-05-20 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0006_splitsheet_isrc_alter_splitsheet_track'),
    ]

    operations = [
        migrations.AddField(
            model_name='splitsheet',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('PENDING', 'Pending signature'), ('SIGNED', 'Signed'), ('EXPIRED', 'Signature expired')], default='CREATED', max_length=20),
        ),
    ]
