# Generated by Django 5.0.3 on 2024-04-07 14:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0005_remove_publishingsplit_track_delete_mastersplit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterSplit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('signature_request_id', models.CharField(blank=True, max_length=50)),
                ('validated', models.DateTimeField(blank=True, default=None, null=True)),
                ('owner_name', models.CharField(blank=True, max_length=250)),
                ('owner_email', models.EmailField(blank=True, max_length=254)),
                ('percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_splits', to='catalog.track')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PublishingSplit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('owner_name', models.CharField(blank=True, max_length=250)),
                ('owner_email', models.EmailField(blank=True, max_length=254)),
                ('percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('signature_request_id', models.CharField(blank=True, max_length=50)),
                ('validated', models.DateTimeField(blank=True, default=None, null=True)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publishing_splits', to='catalog.track')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
