# Generated by Django 5.0.6 on 2024-05-20 17:32

import catalog.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_track_other_distributor_email'),
        ('legal', '0005_alter_splitsheet_track_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='splitsheet',
            name='isrc',
            field=models.CharField(blank=True, max_length=12, validators=[catalog.validators.validate_isrc], verbose_name='ISRC'),
        ),
        migrations.AlterField(
            model_name='splitsheet',
            name='track',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='split_sheet', to='catalog.track'),
        ),
    ]
