# Generated by Django 5.0.6 on 2024-05-22 19:44

import legal.models
import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0007_splitsheet_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='splitsheet',
            name='track_cover_image',
            field=models.ImageField(blank=True, storage=storages.backends.s3.S3Storage(bucket_name=''), upload_to=legal.models.get_upload_path),
        ),
    ]
