# Generated by Django 5.0.6 on 2024-06-11 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0017_artist_artist_artist_uuid_idx_and_more'),
        ('catalog', '0026_genre_catalog_genre_uuid_idx_and_more'),
        ('legal', '0008_splitsheet_track_cover_image'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='splitsheet',
            index=models.Index(fields=['signature_request_id'], name='legal_split_signatu_6ba866_idx'),
        ),
        migrations.AddIndex(
            model_name='splitsheet',
            index=models.Index(fields=['signed'], name='legal_split_signed_d3869c_idx'),
        ),
        migrations.AddIndex(
            model_name='splitsheet',
            index=models.Index(fields=['status'], name='legal_split_status_7ee95e_idx'),
        ),
        migrations.AddIndex(
            model_name='splitsheet',
            index=models.Index(fields=['isrc'], name='legal_split_isrc_b93bf0_idx'),
        ),
    ]
