# Generated by Django 5.0.2 on 2024-02-24 15:33

import catalog.models
import catalog.validators
import common.models
import django.db.models.deletion
import taggit.managers
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artist', '0001_initial'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
                ('code', models.SlugField(max_length=80, unique=True)),
            ],
            options={
                'abstract': False,
                'indexes': [common.models.PostgresIndex(fields=['uuid'], name='catalog_genre_uuid_idx'), common.models.PostgresIndex(fields=['created'], name='catalog_genre_created_idx'), common.models.PostgresIndex(fields=['updated'], name='catalog_genre_updated_idx')],
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('isrc', models.CharField(max_length=12, validators=[catalog.validators.validate_isrc])),
                ('name', models.CharField(max_length=250)),
                ('duration', models.PositiveIntegerField(null=True)),
                ('released', models.DateTimeField(blank=True, null=True)),
                ('is_cover', models.BooleanField(default=False)),
                ('is_remix', models.BooleanField(default=False)),
                ('is_instrumental', models.BooleanField(default=False)),
                ('is_explicit', models.BooleanField(default=False)),
                ('record_type', models.CharField(choices=[('STUDIO', 'Studio')], default='STUDIO', max_length=10)),
                ('bpm', models.PositiveIntegerField(blank=True, null=True)),
                ('language', models.CharField(blank=True, choices=[('EN', 'Enlgish'), ('ES', 'Spanish')], max_length=2)),
                ('lyrics', models.TextField(blank=True)),
                ('snippet', models.FileField(upload_to=catalog.models.get_upload_path)),
                ('file_wav', models.FileField(upload_to=catalog.models.get_upload_path)),
                ('file_mp3', models.FileField(upload_to=catalog.models.get_upload_path)),
                ('additional_main_artists', models.ManyToManyField(blank=True, related_name='other_tracks_main', to='artist.artist')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tracks', to='artist.artist')),
                ('featured_artists', models.ManyToManyField(blank=True, related_name='other_tracks_featured', to='artist.artist')),
                ('genres', models.ManyToManyField(blank=True, related_name='tracks', to='catalog.genre')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='PublishingSplit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('owner_name', models.CharField(blank=True, max_length=250)),
                ('owner_email', models.EmailField(blank=True, max_length=254)),
                ('percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publishing_splits', to='catalog.track')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MasterSplit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('owner_name', models.CharField(blank=True, max_length=250)),
                ('owner_email', models.EmailField(blank=True, max_length=254)),
                ('percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_splits', to='catalog.track')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='track',
            index=models.Index(fields=['isrc'], name='catalog_tra_isrc_18625c_idx'),
        ),
        migrations.AddIndex(
            model_name='publishingsplit',
            index=common.models.PostgresIndex(fields=['uuid'], name='catalog_publishingsplit_uuid_idx'),
        ),
        migrations.AddIndex(
            model_name='publishingsplit',
            index=common.models.PostgresIndex(fields=['created'], name='catalog_publishingsplit_created_idx'),
        ),
        migrations.AddIndex(
            model_name='publishingsplit',
            index=common.models.PostgresIndex(fields=['updated'], name='catalog_publishingsplit_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='mastersplit',
            index=common.models.PostgresIndex(fields=['uuid'], name='catalog_mastersplit_uuid_idx'),
        ),
        migrations.AddIndex(
            model_name='mastersplit',
            index=common.models.PostgresIndex(fields=['created'], name='catalog_mastersplit_created_idx'),
        ),
        migrations.AddIndex(
            model_name='mastersplit',
            index=common.models.PostgresIndex(fields=['updated'], name='catalog_mastersplit_updated_idx'),
        ),
    ]
