# Generated by Django 5.0.3 on 2024-04-07 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_remove_publishingsplit_track_delete_mastersplit_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='genre',
            index=models.Index(fields=['name'], name='catalog_gen_name_351426_idx'),
        ),
        migrations.AddIndex(
            model_name='genre',
            index=models.Index(fields=['code'], name='catalog_gen_code_8b049e_idx'),
        ),
    ]
