# Generated by Django 5.0.4 on 2024-04-29 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0005_artist_background_image_artist_image'),
        ('catalog', '0013_track_cover_image'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='chartmetric_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='spotify_id',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddIndex(
            model_name='track',
            index=models.Index(fields=['spotify_id'], name='catalog_tra_spotify_25e90c_idx'),
        ),
        migrations.AddIndex(
            model_name='track',
            index=models.Index(fields=['chartmetric_id'], name='catalog_tra_chartme_b79974_idx'),
        ),
    ]
