# Generated by Django 5.0.4 on 2024-05-09 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_price_track_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='price',
            options={'ordering': ['order']},
        ),
        migrations.RemoveIndex(
            model_name='price',
            name='catalog_price_uuid_idx',
        ),
        migrations.RemoveIndex(
            model_name='price',
            name='catalog_price_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='price',
            name='catalog_price_updated_idx',
        ),
        migrations.RenameField(
            model_name='price',
            old_name='amount',
            new_name='single_use_price',
        ),
        migrations.AddField(
            model_name='price',
            name='order',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='price',
            index=models.Index(fields=['order'], name='catalog_pri_order_6ba067_idx'),
        ),
    ]
