# Generated by Django 5.0.6 on 2024-05-14 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_remove_track_record_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='other_distributor',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='track',
            name='name',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
