# Generated by Django 5.0.3 on 2024-04-03 18:17

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_genre_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mastersplit',
            name='validated',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='publishingsplit',
            name='percent',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
