# Generated by Django 5.0.3 on 2024-04-03 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_mastersplit_validated_alter_publishingsplit_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='mastersplit',
            name='signature_request_id',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
