# Generated by Django 5.0.3 on 2024-04-07 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_mastersplit_signature_request_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publishingsplit',
            name='track',
        ),
        migrations.DeleteModel(
            name='MasterSplit',
        ),
        migrations.DeleteModel(
            name='PublishingSplit',
        ),
    ]
