# Generated by Django 5.0.4 on 2024-04-22 16:38

import common.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_track_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('contact_name', models.CharField(blank=True, max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'abstract': False,
                'indexes': [common.models.PostgresIndex(fields=['uuid'], name='catalog_distributor_uuid_idx'), common.models.PostgresIndex(fields=['created'], name='catalog_distributor_created_idx'), common.models.PostgresIndex(fields=['updated'], name='catalog_distributor_updated_idx')],
            },
        ),
        migrations.AddField(
            model_name='track',
            name='distributor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracks', to='catalog.distributor'),
        ),
    ]
