# Generated by Django 5.0.4 on 2024-04-23 14:43

import catalog.models
import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_distributor_whitelist_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='distributor',
            options={'ordering': ['name']},
        ),
        migrations.RemoveIndex(
            model_name='distributor',
            name='catalog_distributor_uuid_idx',
        ),
        migrations.RemoveIndex(
            model_name='distributor',
            name='catalog_distributor_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='distributor',
            name='catalog_distributor_updated_idx',
        ),
        migrations.AddField(
            model_name='synclist',
            name='background_image',
            field=models.ImageField(blank=True, storage=storages.backends.s3.S3Storage(bucket_name=''), upload_to=catalog.models.get_sync_upload_path),
        ),
        migrations.AddField(
            model_name='synclist',
            name='cover_image',
            field=models.ImageField(blank=True, storage=storages.backends.s3.S3Storage(bucket_name=''), upload_to=catalog.models.get_sync_upload_path),
        ),
        migrations.AlterField(
            model_name='track',
            name='file_mp3',
            field=models.FileField(blank=True, upload_to=catalog.models.get_upload_path),
        ),
        migrations.AlterField(
            model_name='track',
            name='file_wav',
            field=models.FileField(blank=True, upload_to=catalog.models.get_upload_path),
        ),
        migrations.AlterField(
            model_name='track',
            name='snippet',
            field=models.FileField(blank=True, upload_to=catalog.models.get_upload_path),
        ),
    ]
