# Generated by Django 5.0.4 on 2024-04-29 09:59

import catalog.models
import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_alter_distributor_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='cover_image',
            field=models.ImageField(blank=True, storage=storages.backends.s3.S3Storage(bucket_name=''), upload_to=catalog.models.get_upload_path),
        ),
    ]
