# Generated by Django 5.0.4 on 2024-04-29 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_track_chartmetric_id_track_spotify_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='chartmetric_id',
            field=models.CharField(blank=True, default='', max_length=30),
            preserve_default=False,
        ),
    ]
