# Generated by Django 5.0.4 on 2024-05-04 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_alter_track_chartmetric_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='language',
            field=models.CharField(blank=True, choices=[('EN', 'English'), ('ES', 'Spanish')], max_length=2),
        ),
    ]
