# Generated by Django 5.0.4 on 2024-05-09 15:28

import common.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_alter_track_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('max_artist_tracks', models.PositiveIntegerField(default=0, help_text='Use 0 for unlimited', verbose_name='Max tracks per artist')),
                ('default', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
                'indexes': [common.models.PostgresIndex(fields=['uuid'], name='catalog_price_uuid_idx'), common.models.PostgresIndex(fields=['created'], name='catalog_price_created_idx'), common.models.PostgresIndex(fields=['updated'], name='catalog_price_updated_idx')],
            },
        ),
        migrations.AddField(
            model_name='track',
            name='price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracks', to='catalog.price'),
        ),
    ]
