# Generated by Django 5.0.6 on 2024-05-12 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_track_spotify_popularity_alter_track_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='record_type',
        ),
    ]
