# Generated by Django 5.0.6 on 2024-05-28 08:05

import common.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0001_initial'),
        ('catalog', '0022_track_other_distributor_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='single_use_price',
        ),
        migrations.AlterField(
            model_name='price',
            name='max_artist_tracks',
            field=models.PositiveIntegerField(default=0, help_text='Max tracks allowed per artist with this price. Use 0 for unlimited', verbose_name='Max tracks/artist'),
        ),
        migrations.CreateModel(
            name='TierPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('single_use_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('subscription_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tier_prices', to='catalog.price')),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tier_prices', to='buyer.tier')),
            ],
            options={
                'abstract': False,
                'indexes': [common.models.PostgresIndex(fields=['uuid'], name='catalog_tierprice_uuid_idx'), common.models.PostgresIndex(fields=['created'], name='catalog_tierprice_created_idx'), common.models.PostgresIndex(fields=['updated'], name='catalog_tierprice_updated_idx')],
            },
        ),
    ]
