# Generated by Django 5.0.6 on 2024-05-28 08:22

import common.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0017_artist_artist_artist_uuid_idx_and_more'),
        ('catalog', '0025_price_catalog_price_uuid_idx_and_more'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='genre',
            index=common.models.PostgresIndex(fields=['uuid'], name='catalog_genre_uuid_idx'),
        ),
        migrations.AddIndex(
            model_name='genre',
            index=common.models.PostgresIndex(fields=['created'], name='catalog_genre_created_idx'),
        ),
        migrations.AddIndex(
            model_name='genre',
            index=common.models.PostgresIndex(fields=['updated'], name='catalog_genre_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='synclist',
            index=common.models.PostgresIndex(fields=['uuid'], name='catalog_synclist_uuid_idx'),
        ),
        migrations.AddIndex(
            model_name='synclist',
            index=common.models.PostgresIndex(fields=['created'], name='catalog_synclist_created_idx'),
        ),
        migrations.AddIndex(
            model_name='synclist',
            index=common.models.PostgresIndex(fields=['updated'], name='catalog_synclist_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='track',
            index=common.models.PostgresIndex(fields=['uuid'], name='catalog_track_uuid_idx'),
        ),
        migrations.AddIndex(
            model_name='track',
            index=common.models.PostgresIndex(fields=['created'], name='catalog_track_created_idx'),
        ),
        migrations.AddIndex(
            model_name='track',
            index=common.models.PostgresIndex(fields=['updated'], name='catalog_track_updated_idx'),
        ),
    ]
