# Generated by Django 5.0.6 on 2024-05-28 08:05

import common.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.SlugField(max_length=20)),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
                'indexes': [common.models.PostgresIndex(fields=['uuid'], name='buyer_tier_uuid_idx'), common.models.PostgresIndex(fields=['created'], name='buyer_tier_created_idx'), common.models.PostgresIndex(fields=['updated'], name='buyer_tier_updated_idx')],
            },
        ),
    ]
