# Generated by Django 5.0.6 on 2024-05-28 10:03

import common.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='buyers', to='buyer.tier')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'indexes': [common.models.PostgresIndex(fields=['uuid'], name='buyer_buyer_uuid_idx'), common.models.PostgresIndex(fields=['created'], name='buyer_buyer_created_idx'), common.models.PostgresIndex(fields=['updated'], name='buyer_buyer_updated_idx')],
            },
        ),
    ]
