# Generated by Django 5.0.2 on 2024-02-24 15:33

import django_countries.fields
import taggit.managers
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=250)),
                ('bio', models.TextField(blank=True)),
                ('hometown', models.CharField(max_length=250)),
                ('country', django_countries.fields.CountryField(default='ES', max_length=2)),
                ('spotify_url', models.URLField(blank=True, null=True)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'ordering': ['-name'],
                'indexes': [models.Index(fields=['name'], name='artist_arti_name_432677_idx')],
            },
        ),
    ]
