# Generated by Django 5.0.4 on 2024-04-29 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0005_artist_background_image_artist_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='spotify_id',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='artist',
            name='chartmetric_id',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
