# Generated by Django 5.0.4 on 2024-04-29 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0008_artist_instagram_followers_artist_spotify_followers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='instagram_followers',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='artist',
            name='spotify_followers',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='artist',
            name='spotify_monthly_listeners',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='artist',
            name='spotify_popularity',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='artist',
            name='tiktok_followers',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='artist',
            name='tiktok_likes',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
