# Generated by Django 5.0.4 on 2024-05-04 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='active',
            new_name='published',
        ),
    ]
