# Generated by Django 5.0.4 on 2024-05-10 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0010_artist_artist_arti_spotify_9cfa31_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='slug',
            field=models.SlugField(blank=True, max_length=100),
        ),
    ]
