# Generated by Django 5.0.6 on 2024-05-22 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0014_artist_kamrank'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='hubspot_id',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
