# Generated by Django 5.0.6 on 2024-05-28 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0015_artist_hubspot_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='hometown',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
