# Generated by Django 5.0.6 on 2024-05-28 08:22

import common.models
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0016_alter_artist_hometown'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='artist',
            index=common.models.PostgresIndex(fields=['uuid'], name='artist_artist_uuid_idx'),
        ),
        migrations.AddIndex(
            model_name='artist',
            index=common.models.PostgresIndex(fields=['created'], name='artist_artist_created_idx'),
        ),
        migrations.AddIndex(
            model_name='artist',
            index=common.models.PostgresIndex(fields=['updated'], name='artist_artist_updated_idx'),
        ),
    ]
