# Generated by Django 5.0.6 on 2024-06-22 11:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0017_artist_artist_artist_uuid_idx_and_more'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='isni',
            field=models.CharField(blank=True, max_length=16, verbose_name='ISNI'),
        ),
        migrations.AddIndex(
            model_name='artist',
            index=models.Index(fields=['isni'], name='artist_arti_isni_0bacd9_idx'),
        ),
    ]
