# Generated by Django 5.0.2 on 2024-02-28 11:45

import catalog.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['name']},
        ),
        migrations.RemoveIndex(
            model_name='genre',
            name='catalog_genre_uuid_idx',
        ),
        migrations.RemoveIndex(
            model_name='genre',
            name='catalog_genre_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='genre',
            name='catalog_genre_updated_idx',
        ),
        migrations.AlterField(
            model_name='track',
            name='bpm',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='BPM'),
        ),
        migrations.AlterField(
            model_name='track',
            name='isrc',
            field=models.CharField(max_length=12, validators=[catalog.validators.validate_isrc], verbose_name='ISRC'),
        ),
    ]
