# Generated by Django 5.0.3 on 2024-04-07 19:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0003_artist_user'),
        ('catalog', '0006_genre_catalog_gen_name_351426_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('pinned', models.BooleanField(default=True, help_text='Pinned in artist profile.')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='synclists', to='artist.artist')),
            ],
        ),
        migrations.CreateModel(
            name='SyncListTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('synclist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.synclist')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.track')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='synclist',
            name='tracks',
            field=models.ManyToManyField(blank=True, related_name='synclists', through='catalog.SyncListTrack', to='catalog.track'),
        ),
        migrations.AddIndex(
            model_name='synclisttrack',
            index=models.Index(fields=['order'], name='catalog_syn_order_5204e9_idx'),
        ),
        migrations.AddIndex(
            model_name='synclisttrack',
            index=models.Index(fields=['synclist', 'order'], name='catalog_syn_synclis_93d3f6_idx'),
        ),
        migrations.AddIndex(
            model_name='synclist',
            index=models.Index(fields=['order'], name='catalog_syn_order_55279a_idx'),
        ),
    ]
