# Generated by Django 5.0.3 on 2024-04-08 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_synclist_synclisttrack_synclist_tracks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='released',
            field=models.DateField(blank=True, null=True),
        ),
    ]
