# Generated by Django 5.0.4 on 2024-04-22 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_distributor_track_distributor'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributor',
            name='whitelist_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='distributor',
            name='whitelist_send',
            field=models.BooleanField(default=False),
        ),
    ]
