# Generated by Django 5.0.6 on 2024-05-11 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_alter_price_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='spotify_popularity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='track',
            name='duration',
            field=models.PositiveIntegerField(help_text='Duration in milliseconds', null=True),
        ),
    ]
