# Generated by Django 5.0.6 on 2024-05-20 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_track_other_distributor_alter_track_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='other_distributor_email',
            field=models.EmailField(blank=True, max_length=100),
        ),
    ]
