# Generated by Django 5.0.6 on 2024-05-28 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0001_initial'),
        ('catalog', '0023_remove_price_single_use_price_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='tierprice',
            name='catalog_tierprice_uuid_idx',
        ),
        migrations.RemoveIndex(
            model_name='tierprice',
            name='catalog_tierprice_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='tierprice',
            name='catalog_tierprice_updated_idx',
        ),
        migrations.AddConstraint(
            model_name='tierprice',
            constraint=models.UniqueConstraint(fields=('tier', 'price'), name='unique_tier_price'),
        ),
    ]
