# Generated by Django 5.0.6 on 2024-05-28 08:21

import common.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0001_initial'),
        ('catalog', '0024_remove_tierprice_catalog_tierprice_uuid_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='price',
            index=common.models.PostgresIndex(fields=['uuid'], name='catalog_price_uuid_idx'),
        ),
        migrations.AddIndex(
            model_name='price',
            index=common.models.PostgresIndex(fields=['created'], name='catalog_price_created_idx'),
        ),
        migrations.AddIndex(
            model_name='price',
            index=common.models.PostgresIndex(fields=['updated'], name='catalog_price_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='tierprice',
            index=common.models.PostgresIndex(fields=['uuid'], name='catalog_tierprice_uuid_idx'),
        ),
        migrations.AddIndex(
            model_name='tierprice',
            index=common.models.PostgresIndex(fields=['created'], name='catalog_tierprice_created_idx'),
        ),
        migrations.AddIndex(
            model_name='tierprice',
            index=common.models.PostgresIndex(fields=['updated'], name='catalog_tierprice_updated_idx'),
        ),
    ]
