# Generated by Django 5.0.4 on 2024-05-04 05:56

import common.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_alter_track_language'),
        ('legal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mastersplit',
            old_name='owner_name',
            new_name='legal_name',
        ),
        migrations.RenameField(
            model_name='publishingsplit',
            old_name='owner_name',
            new_name='legal_name',
        ),
        migrations.RemoveField(
            model_name='mastersplit',
            name='owner_email',
        ),
        migrations.RemoveField(
            model_name='mastersplit',
            name='signature_request_id',
        ),
        migrations.RemoveField(
            model_name='mastersplit',
            name='track',
        ),
        migrations.RemoveField(
            model_name='mastersplit',
            name='validated',
        ),
        migrations.RemoveField(
            model_name='publishingsplit',
            name='owner_email',
        ),
        migrations.RemoveField(
            model_name='publishingsplit',
            name='signature_request_id',
        ),
        migrations.RemoveField(
            model_name='publishingsplit',
            name='track',
        ),
        migrations.RemoveField(
            model_name='publishingsplit',
            name='validated',
        ),
        migrations.AddField(
            model_name='mastersplit',
            name='email',
            field=models.EmailField(default='default@acrylic.la', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mastersplit',
            name='name',
            field=models.CharField(default='Demo', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mastersplit',
            name='role',
            field=models.CharField(choices=[('artist', 'Artist'), ('producer', 'Producer'), ('label', 'Record Label'), ('other', 'Other')], default='artist', max_length=20),
        ),
        migrations.AddField(
            model_name='publishingsplit',
            name='email',
            field=models.EmailField(default='default@acrylic.la', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publishingsplit',
            name='ipi',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='IPI number'),
        ),
        migrations.AddField(
            model_name='publishingsplit',
            name='name',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publishingsplit',
            name='pro_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='PRO name'),
        ),
        migrations.AddField(
            model_name='publishingsplit',
            name='role',
            field=models.CharField(choices=[('songwriter', 'Songwriter'), ('composer', 'Composer'), ('producer', 'Producer'), ('lyricist', 'Lyricist'), ('remixer', 'Remixer'), ('other', 'Other')], default='songwriter', max_length=20),
        ),
        migrations.CreateModel(
            name='SplitSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('track_name', models.CharField(max_length=150)),
                ('signed', models.DateTimeField(blank=True, default=None, null=True)),
                ('signature_request_id', models.CharField(blank=True, max_length=50)),
                ('track', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='split_sheets', to='catalog.track')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='mastersplit',
            name='split_sheet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='master_splits', to='legal.splitsheet'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publishingsplit',
            name='split_sheet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='publishing_splits', to='legal.splitsheet'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='splitsheet',
            index=common.models.PostgresIndex(fields=['uuid'], name='legal_splitsheet_uuid_idx'),
        ),
        migrations.AddIndex(
            model_name='splitsheet',
            index=common.models.PostgresIndex(fields=['created'], name='legal_splitsheet_created_idx'),
        ),
        migrations.AddIndex(
            model_name='splitsheet',
            index=common.models.PostgresIndex(fields=['updated'], name='legal_splitsheet_updated_idx'),
        ),
    ]
