# Generated by Django 5.0.4 on 2024-05-05 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0002_rename_owner_name_mastersplit_legal_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mastersplit',
            name='signed',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='publishingsplit',
            name='signed',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
