# Generated by Django 5.0.4 on 2024-05-05 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0010_artist_artist_arti_spotify_9cfa31_idx_and_more'),
        ('legal', '0003_mastersplit_signed_publishingsplit_signed'),
    ]

    operations = [
        migrations.AddField(
            model_name='splitsheet',
            name='artist',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='split_sheets', to='artist.artist'),
            preserve_default=False,
        ),
    ]
