# Generated by Django 5.0.4 on 2024-05-05 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0004_splitsheet_artist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='splitsheet',
            name='track_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
