# Generated by Django 5.0.6 on 2024-06-20 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0009_splitsheet_legal_split_signatu_6ba866_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mastersplit',
            name='legal_name',
        ),
        migrations.RemoveField(
            model_name='publishingsplit',
            name='legal_name',
        ),
        migrations.AlterField(
            model_name='mastersplit',
            name='name',
            field=models.CharField(max_length=250, verbose_name='full legal name'),
        ),
        migrations.AlterField(
            model_name='publishingsplit',
            name='name',
            field=models.CharField(max_length=250, verbose_name='full legal name'),
        ),
    ]
