# Generated by Django 5.0.4 on 2024-04-26 07:48

import artist.models
import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0004_alter_artist_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='background_image',
            field=models.ImageField(blank=True, storage=storages.backends.s3.S3Storage(bucket_name=''), upload_to=artist.models.get_aritst_upload_path),
        ),
        migrations.AddField(
            model_name='artist',
            name='image',
            field=models.ImageField(blank=True, storage=storages.backends.s3.S3Storage(bucket_name=''), upload_to=artist.models.get_aritst_upload_path),
        ),
    ]
