# Generated by Django 5.0.4 on 2024-04-29 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0006_artist_spotify_id_alter_artist_chartmetric_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='chartmetric_id',
            field=models.CharField(blank=True, default='', max_length=30),
            preserve_default=False,
        ),
    ]
