# Generated by Django 5.0.4 on 2024-04-29 17:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0009_alter_artist_instagram_followers_and_more'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='artist',
            index=models.Index(fields=['spotify_id'], name='artist_arti_spotify_9cfa31_idx'),
        ),
        migrations.AddIndex(
            model_name='artist',
            index=models.Index(fields=['chartmetric_id'], name='artist_arti_chartme_157473_idx'),
        ),
        migrations.AddIndex(
            model_name='artist',
            index=models.Index(fields=['-spotify_followers'], name='artist_arti_spotify_88e088_idx'),
        ),
        migrations.AddIndex(
            model_name='artist',
            index=models.Index(fields=['-instagram_followers'], name='artist_arti_instagr_446a9d_idx'),
        ),
    ]
