# Generated by Django 5.0.6 on 2024-05-11 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0013_artist_unique_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='kamrank',
            field=models.PositiveBigIntegerField(editable=False, null=True, verbose_name='KAMRank'),
        ),
    ]
