# Generated by Django 5.0.6 on 2024-05-11 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_account_billing_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='phone',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='tax_id',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
