# Generated by Django 5.0.6 on 2024-05-28 16:22

import common.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_document_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254)),
                ('joined', models.BooleanField()),
            ],
            options={
                'abstract': False,
                'indexes': [common.models.PostgresIndex(fields=['uuid'], name='account_invitation_uuid_idx'), common.models.PostgresIndex(fields=['created'], name='account_invitation_created_idx'), common.models.PostgresIndex(fields=['updated'], name='account_invitation_updated_idx')],
            },
        ),
    ]
