# Generated by Django 5.0.6 on 2024-06-20 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_document_signature_request_id_document_signed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.CharField(choices=[('REVENUE_SHARE', 'Revenue Share Agreement'), ('CONTRACT', 'Contract'), ('TOS', 'Terms of Service'), ('TAX', 'Tax'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
    ]
