# Generated by Django 5.0.6 on 2024-06-22 13:42

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_invitation_invited_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='contract_signed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='signed_document',
            field=models.FileField(blank=True, upload_to=account.models.get_upload_path),
        ),
    ]
